# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beyond' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for Beyond
  pod 'Amplify'
  pod 'AmplifyPlugins'
  target 'BeyondTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BeyondUITests' do
    # Pods for testing
  end

end
